name: Run Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  check:
    runs-on: "ubuntu-latest"
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
      - name: Check
        run: ./gradlew check --continue
      - name: Summarize Detekt
        if: success() || failure()
        run: |
          find \
          domain/build/reports/detekt/ \
          desktop-app/build/reports/detekt/ \
          -name "*.md" \
          -exec cat {} >> $GITHUB_STEP_SUMMARY \;
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif
