name: Run Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
      - name: Check
        run: ./gradlew check --continue
      - name: Summarize Detekt
        if: (success() || failure()) && (hashFiles('domain/build/reports/detekt/**/*.md') != '' || hashFiles('desktop-app/build/reports/detekt/**/*.md') != '')
        run: |
          find \
          domain/build/reports/detekt/ \
          desktop-app/build/reports/detekt/ \
          -type f \
          -name "*.md" \
          -exec cat {} + >> "$GITHUB_STEP_SUMMARY" 2>/dev/null || true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: (success() || failure()) && hashFiles('build/reports/detekt-merged/detekt.sarif') != ''
        with:
          sarif_file: build/reports/detekt-merged/detekt.sarif

