name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Release kind
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        id: version
        uses: reecetech/version-increment@2023.10.2
        with:
          scheme: semver
          increment: ${{ inputs.bump }}
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build
        run: ./gradlew jar --no-daemon
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
      - name: Package
        uses: hydraulic-software/conveyor/actions/build@v13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
        with:
          conveyor_version: 13.1
          agree_to_license: 1
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
      - run: ls -la
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Prepare Download Site
        run: |
          mkdir _site
          mv output/download.html _site/index.html
          mv output/icon.svg _site/icon.svg
      - name: Fix Permissions
        run: |
          chmod -v -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Download Page
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: release

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



