name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Release kind
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - id: release
        name: Create Release
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: HEMAtoma <RELEASE_VERSION>
          bump_version_scheme: ${{ inputs.bump }}
          use_github_release_notes: true
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build
        run: ./gradlew jar --no-daemon
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.tag_name }}
      - name: Package
        uses: hydraulic-software/conveyor/actions/build@v12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.release.outputs.tag_name }}
        with:
          conveyor_version: 13.1
          agree_to_license: 1
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}

