name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Which part of the version to bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - id: release
        name: Create Release
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: HEMAtoma <RELEASE_VERSION>
          bump_version_scheme: ${{ inputs.bump }}
          use_github_release_notes: true
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}

  package:
    needs: version
    strategy:
      matrix:
        variant:
          - { os: windows-latest, package: exe }
          - { os: ubuntu-latest, package: deb }
    runs-on: ${{ matrix.variant.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build & Package
        run: ./gradlew packageDistributionForCurrentOS --no-daemon
        env:
          RELEASE_VERSION: ${{ needs.version.outputs.tag_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.variant.package }}
          path: ${{ github.workspace }}/desktop-app/build/compose/binaries/main/${{ matrix.variant.package }}/*.${{ matrix.variant.package }}

  release:
    needs: [version, package]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: ${{ github.workspace }}/packages
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.tag_name }}
          files: |
            ${{ github.workspace }}/packages/*.deb
            ${{ github.workspace }}/packages/*.exe


