name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Release kind
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: semver
          increment: ${{ inputs.bump }}
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Build
        run: ./gradlew jar --no-daemon
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
      - name: Package
        uses: hydraulic-software/conveyor/actions/build@v17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
        with:
          conveyor_version: 13.1
          agree_to_license: 1
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
